local hit_effects = require("__base__/prototypes/entity/hit-effects")
local sounds = require("__base__/prototypes/entity/sounds")
circuit_connector_definitions["kr-quarry-drill"] = circuit_connector_definitions.create(universal_connector_template, {
  { variation = 0, main_offset = util.by_pixel(5, -118), shadow_offset = util.by_pixel(7, -118), show_shadow = true },
  {
    variation = 2,
    main_offset = util.by_pixel(100, -22),
    shadow_offset = util.by_pixel(102, -22),
    show_shadow = true,
  },
  { variation = 4, main_offset = util.by_pixel(-4, 82), shadow_offset = util.by_pixel(-2, 82), show_shadow = true },
  {
    variation = 6,
    main_offset = util.by_pixel(-100, -15),
    shadow_offset = util.by_pixel(-98, -15),
    show_shadow = true,
  },
})

data:extend({
  {
    type = "mining-drill",
    name = "kr-quarry-drill",
    icon = "__SpaceG__/graphics/quarry-drill.png",
    icon_size = 64,
    icon_mipmaps = 4,
    flags = { "placeable-neutral", "player-creation" },
    minable = { mining_time = 1, result = "kr-quarry-drill" },
    damaged_trigger_effect = hit_effects.entity(),
    --fast_replaceable_group = "kr-quarry-drills",
    max_health = 1000,
    resource_categories = { "kr-quarry" },
    --corpse = "kr-big-random-pipes-remnant",
    dying_explosion = "big-explosion",
    resistances = {
      { type = "physical", percent = 50 },
      { type = "fire", percent = 70 },
      { type = "impact", percent = 70 },
    },
    collision_box = { { -3.3, -3.3 }, { 3.3, 3.3 } },
    selection_box = { { -3.5, -3.5 }, { 3.5, 3.5 } },
    module_specification = { module_slots = 2 },
    allowed_effects = { "consumption", "speed", "productivity", "pollution" },
    energy_source = {
      type = "electric",
      usage_priority = "secondary-input",
      emissions_per_minute = 100,
    },
    energy_usage = "2.5MW",
    mining_speed = 10,
    mining_power = 3,
    resource_searching_radius = 0.49,
    vector_to_place_result = { 0, -3.65 },
    radius_visualisation_picture = {
      filename = "__base__/graphics/entity/electric-mining-drill/electric-mining-drill-radius-visualization.png",
      width = 12,
      height = 12,
    },
    animations = {
      layers = {
        {
          priority = "extra-high",
          filename = "__SpaceG__/graphics/quarry-drill/quarry-drill-light.png",
          width = 220,
          height = 232,
          frame_count = 90,
          line_length = 10,
          shift = { 0, -0.18 },
          draw_as_light = true,
          blend_mode = "additive",
          flags = { "light" },
          animation_speed = 0.3,
          scale = 1.04,
          hr_version = {
            priority = "extra-high",
            filename = "__SpaceG__/graphics/quarry-drill/hr-quarry-drill-light.png",
            width = 440,
            height = 464,
            frame_count = 90,
            line_length = 10,
            shift = { 0, -0.18 },
            draw_as_light = true,
            blend_mode = "additive",
            flags = { "light" },
            animation_speed = 0.3,
            scale = 0.52,
          },
        },
        {
          priority = "high",
          filename = "__SpaceG__/graphics/quarry-drill/quarry-drill.png",
          width = 220,
          height = 232,
          frame_count = 90,
          line_length = 10,
          shift = { 0, -0.18 },
          animation_speed = 0.3,
          scale = 1.04,
          hr_version = {
            priority = "high",
            filename = "__SpaceG__/graphics/quarry-drill/hr-quarry-drill.png",
            width = 440,
            height = 464,
            frame_count = 90,
            line_length = 10,
            shift = { 0, -0.18 },
            animation_speed = 0.3,
            scale = 0.52,
          },
        },
        {
          priority = "medium",
          filename = "__SpaceG__/graphics/quarry-drill/quarry-drill-sh.png",
          width = 250,
          height = 211,
          frame_count = 1,
          repeat_count = 90,
          shift = { 0, 0.05 },
          draw_as_shadow = true,
          animation_speed = 0.3,
          scale = 1.04,
          hr_version = {
            priority = "medium",
            filename = "__SpaceG__/graphics/quarry-drill/hr-quarry-drill-sh.png",
            width = 500,
            height = 422,
            frame_count = 1,
            repeat_count = 90,
            shift = { 0, 0.05 },
            draw_as_shadow = true,
            animation_speed = 0.3,
            scale = 0.52,
          },
        },
      },
    },
    vehicle_impact_sound = sounds.generic_impact,
    working_sound = {
      sound = {
        filename = "__SpaceG__/sounds/quarry-drill.ogg",
        volume = 0.9,
      },
      idle_sound = { filename = "__base__/sound/idle1.ogg" },
      max_sounds_per_type = 2,
    },
    circuit_wire_connection_points = circuit_connector_definitions["kr-quarry-drill"].points,
    circuit_connector_sprites = circuit_connector_definitions["kr-quarry-drill"].sprites,
    circuit_wire_max_distance = default_circuit_wire_max_distance,
  },

  {
    type = "item",
    name = "kr-quarry-drill",
    icon = "__SpaceG__/graphics/quarry-drill.png",
    icon_size = 64,
    icon_mipmaps = 4,
    subgroup = "extraction-machine",
    order = "a[items]-e[quarry-drill]",
    place_result = "kr-quarry-drill",
    stack_size = 50,
  },

  {
    type = "recipe",
    name = "kr-quarry-drill",
    energy_required = 60,
    enabled = false,
    ingredients = {
      { "low-density-structure", 15 },
      { "steel-plate", 50 },
      { "rare-metals", 50 },
      { "electric-engine-unit", 100 },
      { "processing-unit", 20 },
    },
    result = "kr-quarry-drill",
  },

  {
    type = "recipe",
    name = "imersite-powder",
    category = "crushing",
    icon = "__SpaceG__/graphics/resources/icons/imersite-powder/imersite-powder.png",
    icon_size = 64,
    hide_from_player_crafting = false,
    always_show_made_in = true,
    allow_as_intermediate = false,
    allow_intermediates = false,
    always_show_products = true,
    energy_required = 3,
    enabled = false,
    allow_productivity = true,
    ingredients = {
      { "raw-imersite", 1 },
    },
    results = {
      { "imersite-powder", 1 },
      { "silica", 1 },
    },
    main_product = "imersite-powder",
  },
  {
    type = "recipe",
    name = "imersium-plate",
    category = "advanced-crafting",
    energy_required = 12,
    enabled = false,
    always_show_made_in = true,
    always_show_products = true,
    allow_productivity = true,
    ingredients = {
      { "imersite-powder", 3 },
      { "rare-metals", 2 },
    },
    result = "imersium-plate",
    result_count = 1,
  },
  {
    type = "recipe",
    name = "imersite-crystal",
    category = "chemistry",
    icon = "__SpaceG__/graphics/resources/icons/imersite-crystal/imersite-crystal.png",
    icon_size = 64,
    energy_required = 30,
    enabled = false,
    always_show_made_in = true,
    always_show_products = true,
    allow_productivity = true,
    ingredients = {
      { type = "item", name = "imersite-powder", amount = 6 },
      { type = "fluid", name = "mineral-water", amount = 10 },
      { type = "fluid", name = "sulfuric-acid", amount = 10 },
    },
    result = "imersite-crystal",
    subgroup = "intermediate-product",
    order = "o6[imersite-crystal]",
    crafting_machine_tint = {
      primary = { r = 0.882, g = 0.337, b = 0.890, a = 0.200 },
      secondary = { r = 0.90, g = 0.30, b = 0.25, a = 0.357 },
      tertiary = { r = 0.623, g = 0.270, b = 0.631, a = 0.100 },
      quaternary = { r = 0.882, g = 0.337, b = 0.890, a = 0.900 },
    },
  },

  {
    type = "recipe",
    name = "rare-metals",
    icons = {
      { icon = "__SpaceG__/graphics/resources/icons/rare-metals/rare-metals.png", icon_size = 64 },
      {
        icon = "__SpaceG__/graphics/resources/icons/raw-rare-metals/raw-rare-metals.png",
        icon_size = 64,
        scale = 0.22,
        shift = { -8, -8 },
      },
    },
    category = "smelting",
    subgroup = "raw-material",
    energy_required = 4,
    enabled = true,
    always_show_made_in = true,
    always_show_products = true,
    allow_productivity = true,
    ingredients = {
      { "raw-rare-metals", 2 },
    },
    result = "rare-metals",
    result_count = 1,
  },

	{
		type = "recipe",
		name = "y_crusher",
		icon_size = 32, icon =  "__SpaceG__/graphics/crusher33_icon.png",
		enabled = "false",
		ingredients = {
      {"steel-plate", 2},
      {"iron-gear-wheel", 5},
      {"electronic-circuit", 4},
      {"stone-brick", 3},
    },
		results=
		{
			{type="item", name="y_crusher", amount=1, }
		},
		-- subgroup = "y_line1",
	},

	{
		type = "item",
		name = "y_crusher",
		icon_size = 32, icon =  "__SpaceG__/graphics/crusher33_icon.png",
--		group = "productivity",
		subgroup = "production-machine",
		order = "c1",
		place_result = "y_crusher",
		stack_size = 25,
	},

	{
		type = "assembling-machine",
		name = "y_crusher",
		icon_size = 32, icon =  "__SpaceG__/graphics/crusher33_icon.png",
		flags = {"placeable-neutral","player-creation"},
		minable = {hardness = 0.5, mining_time = 1, result = "y_crusher"},
		max_health = 200,
		resistances = {{type = "physical",percent = 50}},
		collision_box = {{-1.2,-1.2},{1.2,1.2}},
		selection_box = {{-1.5,-1.5},{1.5,1.5}},
		animation = {
			filename = "__SpaceG__/graphics/crusher33_sheet.png",
			priority = "medium", width = 128, height = 128, frame_count = 12, shift = {0.5, 0}, animation_speed=0.5,
		},
    working_sound = {
      sound = {
        filename = "__SpaceG__/sounds/crusher.ogg",
        volume = 0.8,
      },
      idle_sound = { filename = "__base__/sound/idle1.ogg" },
      max_sounds_per_type = 2,
    },

		crafting_categories = {"crushing"},
		crafting_speed = 1.5,
		energy_source = {type = "electric", input_priority = "secondary", usage_priority = "secondary-input", emissions_per_minute = 3.0, },
		energy_usage = "250kW",
		ingredient_count = 1,
		module_specification =
		{
			module_slots = 2
		},
		allowed_effects = {"consumption", "speed", "productivity", "pollution"},
	},

})
